# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

  inhibit_all_warnings! 

target 'Storage photo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Storage photo
  
  pod 'SwiftyKeychainKit', '1.0.0-beta.2'

end
